#
# Copyright (C) 2021 Transaction Processing Performance Council (TPC) and/or its contributors.
# This file is part of a software package distributed by the TPC
# The contents of this file have been developed by the TPC, and/or have been licensed to the TPC under one or more contributor
# license agreements.
# This file is subject to the terms and conditions outlined in the End-User
# License Agreement (EULA) which can be found in this distribution (EULA.txt) and is available at the following URL:
# http://www.tpc.org/TPC_Documents_Current_Versions/txt/EULA.txt
# Unless required by applicable law or agreed to in writing, this software is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, and the user bears the entire risk as to quality
# and performance as well as the entire cost of service or repair in case of defect. See the EULA for more details.
#


#
# Copyright 2019 Intel Corporation.
# This software and the related documents are Intel copyrighted materials, and your use of them
# is governed by the express license under which they were provided to you ("License"). Unless the
# License provides otherwise, you may not use, modify, copy, publish, distribute, disclose or
# transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.
#
#


name: python-venv
channels:
  - pytorch
  - conda-forge
  - default
dependencies:
#default
#-workloads
  - python=3.7.3
#-driver
  - pyyaml=6.0
  - matplotlib=3.5.0
  - jinja2=3.0.2
  - pandas=1.2.4
  - scikit-learn=1.0.2
  - pycryptodome=3.12
  - numpy=1.20.3

  # provided in dl venv config file
  - tensorflow=2.2.0
  - gcc_linux-64=7.3 #=9.3
  - gxx_linux-64=7.3 #=9.3
  - openmpi-mpicc=4.0.5 #=4.0  ----#4.1.3
  - h5py=2.10.0 #=2.10
  - tqdm=4.62.3 # ----#4.64
  - joblib=1.1.0 #
  - py-opencv=4.5.1 #>=4.5
  - dlib==19.20.0 #==19.20
  - librosa==0.8.1

  #- nccl
  #- fsspec=2022.5
  #- protobuf=3.8  
  #- nvcc_linux-64=10.2
  #- cudnn #8.2.1.32
  #- cupti #11.3.1
  #- cxx-compiler
  #- bokeh #2.4.3
  #- cmake=3.16
  
# pip
  - pip
  - pip:
    - tensorflow-addons==0.10
    - scikit-surprise==1.1.0
    - imbalanced-learn==0.9.0

    - statsmodels==0.12.2
    - xgboost==1.5.0
    - petastorm==0.9.8
    #- horovod[tensorflow] #==0.20
    #- --no-binary=horovod
